global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'prometheus'

  - job_name: 'monitor-service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: '25102005'
    static_configs:
      - targets: ['monitor-service:8081']
        labels:
          app: 'banking-monitor'
