spring:
  application:
    name: orchestration-service
  cloud:
    stream:
      bindings:
        orchestration-input:
          destination: banking-events
          group: orchestration
      function:
        definition: orchestrationSupplier

    config:
      uri: http://config-server:8888
#  datasource:
#    url: jdbc:mysql://mysql:3306/orchestrationdatabase?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000
  redis:
    connection-timeout: 10000
  graphql:
    cors:
      allowed-origins: http://localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/orchestrationdatabase?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    configurations:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permitRequestInHalfOpenState: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

