using System;

namespace NotificationService.Application.CQRS.DTO
{
    public record NotificationSentReply(
        string SagaId,
        string TransactionId, // ID of the fund transfer transaction this notification pertains to
        string NotificationId, // ID of the notification attempt/log generated by NotificationService
        bool Success,
        string FailureReason // Null if successful
    );
} 