spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8088

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/transfers/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/auth/realms/demo