spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8088

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000