spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8088

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/