spring:
  application:
    name: orchestration-service
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    stream:
          bindings:
            orchestration-input:
              destination: banking-events
              group: orchestration
          function:
            definition: orchestrationSupplier

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


redis:
  connection-timeout: 10000