spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orchestrationdatabase?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      bindings:
        orchestration-input:
          destination: banking-events
          group: orchestration
        orchestrationConsumer-in-0:
          destination: orchestration-events
          group: orchestration-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
      function:
        autodetect: true
        definition: orchestrationConsumer