package com.webbanking.notificationservice.dto;

/**
 * Reply message indicating the result of a notification attempt
 */
public record NotificationSentReply(
        String sagaId,
        String transactionId, // ID of the fund transfer transaction this notification pertains to
        String notificationId, // ID of the notification attempt/log generated by NotificationService
        boolean success,
        String failureReason // Null if successful
) {
} 