package com.webbanking.accountservice.application.cqrs.dto;

/**
 * Reply sent by AccountService after attempting to process a CompensateDebitCommand.
 */
public record CompensateDebitReply(
        String sagaId,                     // ID of the saga
        String compensationTransactionId,  // ID of the transaction performing the compensation (generated by AccountService)
        boolean success,                   // True if compensation was successful
        String failureReason               // Null if successful, otherwise describes the failure
) {
} 