spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      profile: dev
      label: main
      enabled: true
      discovery:
        enabled: false
        service-id: config-server

server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
