spring:
  application:
    name: user-service

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      profile: dev
      label: main
      enabled: true
      discovery:
        enabled: false
        service-id: config-server

  datasource:
    url: jdbc:mysql://localhost:3306/banking_user?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "configserver:"

server:
  port: 8231