package com.webbanking.transactionservice.application.cqrs.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Command to instruct TransactionService to record a transaction as part of a fund transfer saga.
 */
public record RecordTransactionCommand(
        String sagaId,
        String transactionId, // The unique ID for this transaction, often generated by the orchestrator
        String sourceAccountId,
        String destinationAccountId,
        BigDecimal amount,
        String currency,
        String transactionType, // e.g., "FUND_TRANSFER", "DEBIT", "CREDIT"
        String status, // e.g., "PENDING_COMPLETION_BY_SAGA", "COMPLETED", "FAILED"
        LocalDateTime initiatedAt,
        String description
) {
} 