spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      discovery:
        enabled: false
        service-id: config-server
      profile: dev
      label: main
  main:
    allow-bean-definition-overriding: true
