server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG
app:
  config:
    keycloak:
      url: http://localhost:8982/
      realm: banking-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/api/fund-transfers/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay=your-keycloak-client-id
        - id: sequence-generator
          uri: lb://sequence-generator
          predicates:
            - Path=/sequence/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/fund-transfers/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          banking-service-client:
            provider: keycloak
            client-id: banking-service-client
            client-secret: R4GSxWcxPyW3QpNxqj4n1fPr9B2OezMb
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8982/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 10000


gateway:
  rate-limiting:
    limit: 100000

#account-service\src\main\resources\application.yml