spring:
  application:
    name: analyze-service
    bad_request: 400
    conflict: 409
    ok: 200
    not_found: 404

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:analyze_service}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
          logging:
            org:
              hibernate:
                type: trace
                level: trace
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8094
  #SequenceGenerator\src\main\resources\application.yml