spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      profile: dev
      label: main
      enabled: true
      discovery:
        enabled: false
        service-id: config-server
app:
  config:
    keycloak:
      server-url: http://localhost:8982
      realm: banking-service
      client-id: banking-service-api-client
      client-secret: BszxUM6j75voyA9yIURScS943zy4AIA7

logging:
  level:
    org:
      keycloak: DEBUG
server:
  port: 8231
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
